server:
  port: 10342

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: book-api
          uri: lb://book-api
          predicates:
            - Path=/book-api/**
          filters:
            - StripPrefix=1
            - AuthorizationHeaderFilter
        - id: user-api
          uri: lb://user-api
          predicates:
            - Path=/user-api/**
          filters:
            - StripPrefix=1
            - AuthorizationHeaderFilter
        - id: order-api
          uri: lb://order-api
          predicates:
            - Path=/order-api/**
          filters:
            - StripPrefix=1
            - AuthorizationHeaderFilter
        - id: coupon-api
          uri: lb://coupon-api
          predicates:
            - Path=/coupon-api/**
          filters:
            - StripPrefix=1
            - AuthorizationHeaderFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
            - AuthorizationHeaderFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10344/eureka,http://localhost:10345/eureka
    register-with-eureka: true
    fetch-registry: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Auth-Service
        url: /auth-service/v3/api-docs