spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: book-api
          uri: lb://book-api
          predicates:
            - Path=/book-api/**
          filters:
            - StripPrefix=1
        - id: user-api
          uri: lb://user-api
          predicates:
            - Path=/user-api/**
          filters:
            - StripPrefix=1
        - id: order-api
          uri: lb://order-api
          predicates:
            - Path=/order-api/**
          filters:
            - StripPrefix=1
        - id: coupon-api
          uri: lb://coupon-api
          predicates:
            - Path=/coupon-api/**
          filters:
            - StripPrefix=1